### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Elayaraman-Ramalingam** [comment]
Created a new issue [Form validation #3](https://github.com/fssa-batch3/elayaraman.ramalingam__web_project/issues/3) in GitHub

**Comment by Elayaraman-Ramalingam** [comment]
Created a new issue [Navigation throughout the page #4](https://github.com/fssa-batch3/elayaraman.ramalingam__web_project/issues/4) in GitHub

**Comment by Elayaraman-Ramalingam** [comment]
Created a new issue [Uploading profile picture #5](https://github.com/fssa-batch3/elayaraman.ramalingam__web_project/issues/5) in GitHub

**Comment by Irfuirfu** [comment]
Created a new issue [Chat page #7](https://github.com/fssa-batch3/elayaraman.ramalingam__web_project/issues/7) in GitHub

**Comment by Irfuirfu** [comment]
Created a new issue [Profile page #8](https://github.com/fssa-batch3/elayaraman.ramalingam__web_project/issues/8) in GitHub

**Comment by Irfuirfu** [comment]
Created a new issue [Edit page #9](https://github.com/fssa-batch3/elayaraman.ramalingam__web_project/issues/9) in GitHub

**Comment by Irfuirfu** [comment]
Created a new issue [Home page #10](https://github.com/fssa-batch3/elayaraman.ramalingam__web_project/issues/10) in GitHub

**Comment by Irfuirfu** [comment]
Created a new issue [Request Page #11](https://github.com/fssa-batch3/elayaraman.ramalingam__web_project/issues/11) in GitHub

**Comment by Irfuirfu** [comment]
Created a new issue [Request page #12](https://github.com/fssa-batch3/elayaraman.ramalingam__web_project/issues/12) in GitHub

**Pull request merged**
